service: tileserverless

frameworkVersion: ">=1.73.0 <2.0.0"

plugins:
  - serverless-offline
  - serverless-content-encoding
  - serverless-plugin-custom-binary

package:
  exclude:
    - .git/**
    - src/**
    - .*
    - tsconfig.*
    - package-lock.json
    - yarn.lock
    - README.md
    - serverless-*.yml

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  region: ap-northeast-1
  logs:
    restApi: true

  stage: dev
  # vpc:
  #   securityGroupIds:
  #     - ${self:custom.sgId}
  #   subnetIds:
  #     - ${self:custom.subnetId}
  # environment:
  #   MOUNT_PATH: ${self:custom.mountPath}
  #
  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #       - "elasticfilesystem:ClientMount"
  #       - "elasticfilesystem:ClientWrite"
  #     Resource:
  #       - Fn::Join:
  #           - ":"
  #           - - arn:aws:elasticfilesystem
  #             - ${self:provider.region}
  #             - Ref: "AWS::AccountId"
  #             - access-point/${self:custom.accessPointId}

custom:
  #   sgId: ${cf:tileserverless-network-${opt:stage, self:provider.stage}.LambdaSecurityGroupId}
  #   subnetId: ${cf:tileserverless-network-${opt:stage, self:provider.stage}.SubnetId}
  #   fsId: ${cf:tileserverless-storage-${opt:stage, self:provider.stage}.FileSystemId}
  #   accessPointId: ${cf:tileserverless-storage-${opt:stage, self:provider.stage}.FileSystemAccessPointId}
  #   mountPath: /mnt/data
  contentEncoding:
    minimumCompressionSize: 0
  apiGateway:
    binaryMediaTypes:
      - "application/x-protobuf"
      - "application/vnd.mapbox-vector-tile"

# on Progress🚀
# https://github.com/serverless/serverless/issues/7848
# fileSystemConfig:
#   - fileSystemId: ${self:custom.fsId}
#     accessPointId: ${self:custom.accessPointId}
#     mountPath: ${self:custom.MOUNT_PATH}

functions:
  tile:
    handler: dist/tile.handler
    events:
      - http:
          path: /{proxy+}
          method: get
          integration: lambda-proxy
          contentHandling: CONVERT_TO_BINARY
          cors:
            origin: "*"
            maxAge: 86400
