service: tileserverless-storage

frameworkVersion: ">=1.73.0 <2.0.0"

provider:
  name: aws
  region: ap-northeast-1
  stage: dev

custom:
  sgId: ${cf:tileserverless-network-${opt:stage, self:provider.stage}.LambdaSecurityGroupId}
  subnetId: ${cf:tileserverless-network-${opt:stage, self:provider.stage}.SubnetId}
  mountPath: /data

resources:
  Resources:
    TileServerlessEFS:
      Type: "AWS::EFS::FileSystem"

    TileServerlessEFSMountTarget:
      Type: "AWS::EFS::MountTarget"
      Properties:
        FileSystemId: !Ref TileServerlessEFS
        SubnetId: ${self:custom.subnetId}
        SecurityGroups:
          - ${self:custom.sgId}

    TileServerlessEFSAccessPoint:
      Type: "AWS::EFS::AccessPoint"
      Properties:
        FileSystemId: !Ref TileServerlessEFS
        PosixUser:
          Uid: 1000
          Gid: 1000
        RootDirectory:
          Path: ${self:custom.mountPath}
          CreationInfo:
            OwnerUid: 1000
            OwnerGid: 1000
            Permissions: "0777"

  Outputs:
    FileSystemId:
      Value: !Ref TileServerlessEFS
    FileSystemAccessPointId:
      Value: !Ref TileServerlessEFSAccessPoint
