service: tileserverless-network

frameworkVersion: ">=1.73.0 <2.0.0"

provider:
  name: aws
  region: ap-northeast-1
  stage: dev

resources:
  Resources:
    TileServerlessVPC:
      Type: "AWS::EC2::VPC"
      Properties:
        CidrBlock: 10.0.0.0/16
        EnableDnsSupport: true
        EnableDnsHostnames: true

    TileServerlessEFSSecurityGroup:
      Type: "AWS::EC2::SecurityGroup"
      Properties:
        GroupDescription: EFS
        VpcId: !Ref TileServerlessVPC
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 2049
            ToPort: 2049
            SourceSecurityGroupId: !Ref TileServerlessLambdaSecurityGroup

    TileServerlessLambdaSecurityGroup:
      Type: "AWS::EC2::SecurityGroup"
      Properties:
        GroupDescription: Lambda
        VpcId: !Ref TileServerlessVPC

    MySubnet:
      Type: "AWS::EC2::Subnet"
      Properties:
        AvailabilityZone: ap-northeast-1a
        VpcId: !Ref TileServerlessVPC
        CidrBlock: 10.0.0.0/24

  Outputs:
    VpcId:
      Value: !Ref TileServerlessVPC
    EFSSecurityGroupId:
      Value: !Ref TileServerlessEFSSecurityGroup
    LambdaSecurityGroupId:
      Value: !Ref TileServerlessLambdaSecurityGroup
    SubnetId:
      Value: !Ref MySubnet
