service: tileserverless

frameworkVersion: ">=1.75.1 <2.0.0"

plugins:
  - serverless-content-encoding

package:
  exclude:
    - .git/**
    - src/**
    - .*
    - tsconfig.*
    - package-lock.json
    - yarn.lock
    - README.md
    - serverless-*.yml

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  region: ap-northeast-1
  apiGateway:
    binaryMediaTypes:
      - "application/x-protobuf"
      - "application/vnd.mapbox-vector-tile"

  stage: dev
  # vpc:
  #   securityGroupIds:
  #     - ${self:custom.sgId}
  #   subnetIds:
  #     - ${self:custom.subnetId}
  # environment:
  #   MOUNT_PATH: ${self:custom.mountPath}
  #
  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #       - "elasticfilesystem:ClientMount"
  #       - "elasticfilesystem:ClientWrite"
  #     Resource:
  #       - Fn::Join:
  #           - ":"
  #           - - arn:aws:elasticfilesystem
  #             - ${self:provider.region}
  #             - Ref: "AWS::AccountId"
  #             - access-point/${self:custom.accessPointId}

# custom:
#   sgId: ${cf:tileserverless-network-${opt:stage, self:provider.stage}.LambdaSecurityGroupId}
#   subnetId: ${cf:tileserverless-network-${opt:stage, self:provider.stage}.SubnetId}
#   fsId: ${cf:tileserverless-storage-${opt:stage, self:provider.stage}.FileSystemId}
#   accessPointId: ${cf:tileserverless-storage-${opt:stage, self:provider.stage}.FileSystemAccessPointId}
#   mountPath: /mnt/data
custom:
  contentEncoding:
    minimumCompressionSize: 0

# on Progress🚀
# https://github.com/serverless/serverless/issues/7848
# fileSystemConfig:
#   - fileSystemId: ${self:custom.fsId}
#     accessPointId: ${self:custom.accessPointId}
#     mountPath: ${self:custom.MOUNT_PATH}

functions:
  tile:
    handler: dist/tile.handler
    events:
      - http:
          path: tiles/{proxy+}
          method: get
          integration: lambda
          response:
            contentHandling: CONVERT_TO_BINARY
            headers:
              "Content-Type": "'application/vnd.mapbox-vector-tile'"
              "Access-Control-Allow-Origin": "'*''"
            200:
              pattern: ".*"
            204:
              pattern: '.*"statusCode":204,.*'

  test:
    handler: dist/single.handler
    events:
      - http:
          path: single
          method: get
          integration: lambda
          response:
            contentHandling: CONVERT_TO_BINARY
            headers:
              Content-Type: "'application/vnd.mapbox-vector-tile'"
              Access-Control-Allow-Origin: "'*''"
